### ISSUE TITLE
I have a question for _pre_process in a class RealNVP

### ISSUE THREAD

**Issue by heeseungsnlp** [chrischute/real-nvp#1]
Hello, I have a question for a function _pre_process.

In the original paper, author preprocessed CIFAR this way. y = alpha + (1 - alpha) * x / 256 (alpha = 0.05, *: elementwise multiplication)

In your code, formula seems a bit different from the original paper like this. y = log({0.5 + x/256 * alpha - alpha / 2} / {0.5 - x/256 * alpha + alpha / 2}). (alpha = 0.9)

I want to know if there is a reason you used different preprocessing.

Thank you for wonderful code and sorry for my pool English.

(I think it's because log(x / 1-x) is inverse function of sigmoid, so I close this issue)

**Comment by saandeepa93** [comment]
Hello, can you please provide more details on why the preprocessing is different?
