### ISSUE TITLE
Training stop with error

### ISSUE THREAD

**Issue by xiamengqi2012** [chrischute/real-nvp#2]
Hi, I tried to follow the instruction and run the training example but at the end of Epoch0 I got the following error message. I followed the Conda environment set-up in the instruction. I am wondering if you know what caused this issue. Thanks!

Traceback (most recent call last):
  File "train.py", line 152, in <module>
    main(parser.parse_args())
  File "train.py", line 63, in main
    test(epoch, net, testloader, device, loss_fn, args.num_samples)
  File "train.py", line 132, in test
    torchvision.utils.save_image(images_concat, 'samples/epoch_{}.png'.format(epoch))
  File "/home/mx83/anaconda3/envs/rnvp/lib/python3.7/site-packages/torchvision/utils.py", line 102, in save_image
    ndarr = grid.mul(255).clamp(0, 255).byte().permute(1, 2, 0).cpu().numpy()
RuntimeError: PyTorch was compiled without NumPy support

**Comment by chrischute** [comment]
I'm not quite sure but I would try the following steps:

1. Make sure you've activated the `rnvp` environment
2. Make sure numpy is installed (check output of `conda env export`)
3. Uninstall and re-install PyTorch: 
```
conda uninstall pytorch
pip uninstall torch
pip uninstall torch # run this command twice
conda install -c pytorch pytorch torchvision
```

Let me know if this works!

**Comment by xiamengqi2012** [comment]
Uninstall and reinstall PyTorch works for me! Thanks a lot!
