### ISSUE TITLE
Affine Coupling Layer computations deviate slightly from article. 

### ISSUE THREAD

**Issue by AlexanderMath** [chrischute/real-nvp#4]
Thanks for an amazing open source version of RealNVP. 

The forward pass for coupling layer computes

https://github.com/chrischute/real-nvp/blob/df51ad570baf681e77df4d2265c0f1eb1b5b646c/models/real_nvp/coupling_layer.py#L62

While RealNVP suggested

![image](https://user-images.githubusercontent.com/8614529/66116490-1aae4700-e5d3-11e9-877a-7937ae37749a.png)

I suspect the difference in performance in negligible, but I felt it might be worth sharing.

**Comment by Newbeeer** [comment]
I also meet this issure too.

**Comment by HobbitLong** [comment]
It's a bit subtle, but I think the author's implementation here is correct. If you think about the value of s and t for `x[1:d]`, you will see `s = s * (1 - b)` and `t = t * (1 - b)` play the trick. Hope it helps.
