### ISSUE TITLE
Synthetic Data I Generated is Rotated

### ISSUE THREAD

**Issue by HanjingWang** [chrischute/real-nvp#5]
Hi,

Thank you so much for the wonderful code. I am new to this area and I want to use RNVP method to learn the joint probability of digit images. I tried MNIST dataset and the samples I got are rotated digits. For example, I would get 3 and E. Some images is vertically symmetrical.

It seems like there is a data augmentation process. However, I do not know why it happens. Hope this question will not bother you too much.

**Comment by chrischute** [comment]
Hi @HanjingWang,

You'll notice that [train.py uses random horizontal flips](https://github.com/chrischute/real-nvp/blob/master/train.py#L25). This makes sense for the natural images found in CIFAR-10, but probably not for the digits in MNIST. As you pointed out digits aren't all symmetric about the Y axis. I would go ahead and turn that setting off for MNIST.

-Chris

**Comment by HanjingWang** [comment]
Thank you so much for your help. Now it works.
