### ISSUE TITLE
What is the value of the loss?

### ISSUE THREAD

**Issue by TiJoy** [chrischute/real-nvp#6]
Thanks for your work!
But I have a question about the value of loss, the loss of my trained model after 100 epochs is 7.33e+3 while the loss of the first epoch is 9.91e+3, is it unnormal? And is it means the likelihood is -loss, e.g., -9.91e+3?
By the way, as the loss decrease, bpd is also decrease from bpd=4.65 to bpd=3.44.
Can you tell me the value of your loss?

**Comment by chrischute** [comment]
I'd take a look at equation 3 of the [Real NVP paper](https://arxiv.org/abs/1605.08803). Then compare it to [these lines of code](https://github.com/chrischute/real-nvp/blob/master/models/real_nvp/real_nvp_loss.py#L20-L24).

The loss has 2 parts that get summed together:
  1. The negative log-likelihood of the latent *z* computed using the Gaussian prior, plus
  2. The sum of log-determinants of Jacobians for all layers from *x* -> *z*

BPD is directly computed from the NLL loss numbers, so if your BPD matches mine then your loss also is similar to what mine was.
