### ISSUE TITLE
What is the exact meaning of 'alt_order=True'?

### ISSUE THREAD

**Issue by Big-Wuu** [chrischute/real-nvp#8]
Hello, 
Thanks for your elegant implementation. But I find it hard to understand what 'alt_order=True' means in squeeze_2x2 function.  The tensor operations are really comfusing. Could you explain it in a more intutive way? And does it corresponds to any text in the origin paper?

Thanks.

**Comment by chrischute** [comment]
Please see section 3.5 of the paper for an explanation
